version: '2.0'
services:
  db:
    image: postgres
  elasticsearch:
    image: elasticsearch:alpine
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
  web:
    build: .
    environment:
      - RAILS_ENV=development
      - ELASTICSEARCH_HOST=elasticsearch
      - POSTGRESQL_HOST=db
      - POSTGRESQL_PASSWORD=
      - POSTGRESQL_USERNAME=postgres
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/buggy
    ports:
      - "3000:3000"
    depends_on:
      - db
      - elasticsearch
volumes:
  elasticsearch: {}